##---------------------------------------------------------------------##
# Simulation parameters
uav_platoon:
  n_vehicles: [10, 10, 10]
  initial_pos: [2, 28, 15]
  chase_distance: 10

ugv_platoon:
  n_vehicles: [7, 8, 10]
  initial_pos: [16, 1, 30]
  chase_distance: 10
##---------------------------------------------------------------------##
# Parameter fields
uav_primitives:
  primitives: ['formation', 'formation', 'formation']
  patrolling_nodes: [2, 1]
  chasing_node: [42]

ugv_primitives:
  primitives: ['formation', 'formation', 'formation']
  patrolling_nodes: [2, 1]
  chasing_node: [42]
##---------------------------------------------------------------------##
# Attributes fields
uav:
  primitive: 'formation'
  n_vehicles: []
  target_pos: [-100, -100]
  source_pos: []
  sink_pos: []
  vehicles: []
  centroid_pos: []
  vehicles_id: []
  vehicles_type: 'uav'
  platoon_id: 0
  initial_formation: True
  selected: False
  execute: True
  visible: False
  casualities: []
##---------------------------------------------------------------------##
ugv:
  primitive: 'formation'
  n_vehicles: []
  target_pos: [-100, -100]
  source_pos: []
  sink_pos: []
  vehicles: []
  centroid_pos: []
  vehicles_id: []
  vehicles_type: 'ugv'
  platoon_id: 0
  initial_formation: True
  selected: False
  execute: True
  visible: False
  casualities: []
##---------------------------------------------------------------------##
